export const lessonUiCopy = {
  en: {
    common: {
      clue: 'Clue',
      answer: 'Answer',
      correct: 'Correct',
      notYet: 'Not yet.',
      answerRevealed: 'Answer revealed.',
      connectionFound: 'Connection found.',
      continue: 'Continue →',
      quickPulse: 'Quick Pulse',
      thinkRealWorld: 'Think / real world',
      discover: 'Discover',
      languageControls: 'Language and learning support controls',
      loadingEyebrow: 'EcoPulse / lesson',
      loadingTitle: 'Loading your\nprogress…',
      hideKazakh: 'Hide Қазақша',
      showKazakhMeaning: 'Қазақша meaning',
      quickCheck: 'Quick Pulse →',
      retryConnection: 'Try the connection again.',
      compareNoClue: 'Compare the options and try once more without a clue.',
    },
    choice: {
      reasoningLabel: 'B2 / English reasoning',
      reasoningPlaceholder: 'Write one short sentence in English…',
      reasoningReady: 'Ready to continue',
      reasoningMinimum: 'Write at least three words',
    },
    factMyth: {
      eyebrow: 'Check the claim / fact or myth',
      groupLabel: 'Choose fact or myth',
      fact: 'Fact',
      myth: 'Myth',
      retry: 'Compare the claim with the distinction you just learned, then try once more.',
      claimChecked: 'Claim checked.',
    },
    fill: {
      eyebrow: 'Use the word / type your answer',
      inputLabel: 'Your English word',
      check: 'Check answer →',
      retry: 'Use the word you just learned in context.',
      success: 'Word in context.',
      answerPrefix: 'Answer:',
    },
    matching: {
      eyebrow: 'Connect the meanings / match',
      instruction: 'Choose one meaning for each concept. No dragging is required.',
      meaningFor: 'Meaning for',
      chooseMeaning: 'Choose meaning…',
      check: 'Check matches →',
      retry: 'One or more connections are different. Review the meanings and try once more.',
      success: 'Connections found.',
      revealed: 'Matches revealed.',
    },
    ordering: {
      eyebrow: 'Connect / order the system',
      instruction: 'Use the arrow controls to move each step. Dragging is not required.',
      listLabel: 'Current system order',
      moveUp: 'Move up',
      moveDown: 'Move down',
      check: 'Check order →',
      retry: 'Follow the simplified cause-and-contribution sequence and try once more.',
      revealed: 'Order revealed.',
    },
    reading: {
      eyebrow: 'Read / understand',
      supportNote: 'Read the English passage, then choose the statement it supports best.',
      comprehension: 'Check understanding',
      retry: 'Read the passage once more and compare what each answer actually claims.',
      success: 'Reading understood.',
    },
    listening: {
      eyebrow: 'Listen / understand',
      supportNote: 'Play the English clip before answering. Transcript is always available as support.',
      play: 'Play audio',
      replay: 'Replay',
      playing: 'Playing…',
      checking: 'Checking audio support…',
      unavailable: 'Device audio is unavailable. Open the transcript to continue.',
      playbackFailed: 'Audio could not play. The transcript remains available.',
      deviceVoiceNote: 'MVP audio uses your device voice when a recorded clip is not available.',
      showTranscript: 'Show transcript',
      hideTranscript: 'Hide transcript',
      transcript: 'Transcript',
      listenFirst: 'Play the clip or open the transcript before answering.',
      comprehension: 'Check listening',
      retry: 'Listen once more or use the transcript, then compare what each answer actually claims.',
      success: 'Listening understood.',
      playAria: 'Play the English listening clip',
      replayAria: 'Replay the English listening clip',
    },
    connection: {
      eyebrow: 'Explore connections',
      chainLabel: 'Concept connection chain',
      meaningsLabel: 'Relationship meanings',
    },
    result: {
      targetWords: 'Target words',
      lessonXp: 'Lesson XP',
      totalXp: 'Total Pulse XP',
      nextPulse: 'Next Pulse',
      learningMap: 'Learning map',
      nextLesson: 'Next lesson →',
      returnToLearn: 'Return to Learn →',
      missionOptional: 'Off-screen / optional',
      missionComplete: 'Mission complete',
      takeMission: 'Take mission →',
      seePulse: 'See My Progress →',
      minutes: 'min',
      noPhoto: 'No photo',
      noLocation: 'No location',
    },
    header: {
      totalXp: 'total Pulse XP',
      backAria: 'Exit lesson and return to learning map',
    },
    sources: {
      title: 'How do we know?',
      officialSource: 'official source',
      officialSources: 'official sources',
      intro: 'The scientific ideas in this lesson are grounded in official educational and science-agency material.',
      checked: 'Checked',
    },
    pronunciation: {
      playing: 'Playing…',
      listen: 'Listen',
      unavailable: 'Audio unavailable',
      aria: 'Listen to the English pronunciation using the device voice',
    },
    visuals: {
      atmosphereAria: 'Simplified diagram of Earth and its atmosphere',
      weatherClimateAria: 'Weather now compared with long-term climate patterns',
      glacierAria: 'Simplified glacier cross-section',
      coastAria: 'Simplified coast and sea-level diagram',
      habitatAria: 'Simplified habitat network connecting water, plants, insects and birds',
      habitatGraphAria: 'Habitat network diagram',
      oceanChemistryAria: 'Simplified ocean chemistry concept diagram',
      wildfireRiskAria: 'Simplified dry vegetation and wildfire-risk diagram',
      droughtAria: 'Simplified dry-land and rainfall diagram',
    },
  },
  kk: {
    common: {
      clue: 'Кеңес',
      answer: 'Жауап',
      correct: 'Дұрыс',
      notYet: 'Әзірге емес.',
      answerRevealed: 'Жауап көрсетілді.',
      connectionFound: 'Байланыс табылды.',
      continue: 'Жалғастыру →',
      quickPulse: 'Жылдам тексеру',
      thinkRealWorld: 'Ойлан / нақты жағдай',
      discover: 'Танысу',
      languageControls: 'Тіл және оқу қолдауының басқару элементтері',
      loadingEyebrow: 'EcoPulse / сабақ',
      loadingTitle: 'Прогресің\nжүктелуде…',
      hideKazakh: 'Қазақшаны жасыру',
      showKazakhMeaning: 'Қазақша мағынасы',
      quickCheck: 'Жылдам тексеру →',
      retryConnection: 'Байланысты қайта тексер.',
      compareNoClue: 'Нұсқаларды салыстырып, қосымша кеңессіз тағы бір рет байқап көр.',
    },
    choice: {
      reasoningLabel: 'B2 / ағылшынша reasoning',
      reasoningPlaceholder: 'Ағылшын тілінде бір қысқа сөйлем жаз…',
      reasoningReady: 'Жалғастыруға дайын',
      reasoningMinimum: 'Кемінде үш сөз жаз',
    },
    factMyth: {
      eyebrow: 'Мәлімдемені тексер / факт немесе миф',
      groupLabel: 'Факт немесе мифті таңда',
      fact: 'Факт',
      myth: 'Миф',
      retry: 'Мәлімдемені жаңа үйренген айырмашылықпен салыстырып, тағы бір рет байқап көр.',
      claimChecked: 'Мәлімдеме тексерілді.',
    },
    fill: {
      eyebrow: 'Сөзді қолдан / жауабыңды жаз',
      inputLabel: 'Ағылшынша жауабың',
      check: 'Жауапты тексеру →',
      retry: 'Жаңа үйренген сөзді сөйлемде қолдан.',
      success: 'Сөз контексте қолданылды.',
      answerPrefix: 'Жауап:',
    },
    matching: {
      eyebrow: 'Мағыналарды байланыстыр / сәйкестендір',
      instruction: 'Әр ұғымға бір мағынаны таңда. Сүйреп апару қажет емес.',
      meaningFor: 'Мағынасы',
      chooseMeaning: 'Мағынасын таңда…',
      check: 'Сәйкестікті тексеру →',
      retry: 'Бір немесе бірнеше байланыс сәйкес емес. Мағыналарды қайта қарап, тағы бір рет байқап көр.',
      success: 'Байланыстар табылды.',
      revealed: 'Сәйкестіктер көрсетілді.',
    },
    ordering: {
      eyebrow: 'Байланыстыр / жүйені ретте',
      instruction: 'Әр қадамды жылжыту үшін көрсеткі батырмаларын қолдан. Сүйреп апару қажет емес.',
      listLabel: 'Жүйенің қазіргі реті',
      moveUp: 'Жоғары жылжыту',
      moveDown: 'Төмен жылжыту',
      check: 'Ретті тексеру →',
      retry: 'Қарапайым себеп пен үлес тізбегін қарап, тағы бір рет байқап көр.',
      revealed: 'Дұрыс рет көрсетілді.',
    },
    reading: {
      eyebrow: 'Оқы / түсін',
      supportNote: 'Ағылшын мәтінін оқып, содан кейін оны ең дәл қолдайтын тұжырымды таңда.',
      comprehension: 'Түсінгеніңді тексер',
      retry: 'Мәтінді тағы бір рет оқып, әр жауаптың нақты не айтып тұрғанын салыстыр.',
      success: 'Мәтін түсінілді.',
    },
    listening: {
      eyebrow: 'Тыңда / түсін',
      supportNote: 'Жауап бермес бұрын ағылшын аудиосын ойнат. Қолдау үшін transcript әрқашан қолжетімді.',
      play: 'Аудионы ойнату',
      replay: 'Қайта ойнату',
      playing: 'Ойнатылуда…',
      checking: 'Аудио қолдауы тексерілуде…',
      unavailable: 'Құрылғы аудиосы қолжетімсіз. Жалғастыру үшін transcript-ті аш.',
      playbackFailed: 'Аудионы ойнату мүмкін болмады. Transcript қолжетімді болып қалады.',
      deviceVoiceNote: 'Жазылған аудио болмаған кезде MVP құрылғыңның дауысын қолданады.',
      showTranscript: 'Transcript көрсету',
      hideTranscript: 'Transcript жасыру',
      transcript: 'Transcript',
      listenFirst: 'Жауап бермес бұрын аудионы ойнат немесе transcript-ті аш.',
      comprehension: 'Тыңдағаныңды тексер',
      retry: 'Тағы бір рет тыңда немесе transcript-ті қолдан, содан кейін жауаптардың нақты мағынасын салыстыр.',
      success: 'Аудио түсінілді.',
      playAria: 'Ағылшынша тыңдалым аудиосын ойнату',
      replayAria: 'Ағылшынша тыңдалым аудиосын қайта ойнату',
    },
    connection: {
      eyebrow: 'Байланыс қозғалтқышы',
      chainLabel: 'Ұғымдар байланысы',
      meaningsLabel: 'Байланыс мағыналары',
    },
    result: {
      targetWords: 'Негізгі сөздер',
      lessonXp: 'Сабақ XP',
      totalXp: 'Жалпы Pulse XP',
      nextPulse: 'Келесі қадам',
      learningMap: 'Оқу картасы',
      nextLesson: 'Келесі сабақ →',
      returnToLearn: 'Оқу картасына →',
      missionOptional: 'Экраннан тыс / міндетті емес',
      missionComplete: 'Миссия аяқталды',
      takeMission: 'Миссияны бастау →',
      seePulse: 'My Pulse-ты көру →',
      minutes: 'мин',
      noPhoto: 'Фото қажет емес',
      noLocation: 'Орналасу қажет емес',
    },
    header: {
      totalXp: 'жалпы Pulse XP',
      backAria: 'Сабақтан шығып, оқу картасына оралу',
    },
    sources: {
      title: 'Мұны қайдан білеміз?',
      officialSource: 'ресми дереккөз',
      officialSources: 'ресми дереккөз',
      intro: 'Бұл сабақтағы ғылыми түсініктер ресми білім беру және ғылыми ұйымдардың материалдарына негізделген.',
      checked: 'Тексерілді',
    },
    pronunciation: {
      playing: 'Ойнатылуда…',
      listen: 'Тыңдау',
      unavailable: 'Дыбыс қолжетімсіз',
      aria: 'Ағылшынша айтылуын құрылғы даусымен тыңдау',
    },
    visuals: {
      atmosphereAria: 'Жер мен оның атмосферасының қарапайым сызбасы',
      weatherClimateAria: 'Қазіргі ауа райы мен ұзақ мерзімді климат үлгілерін салыстыру',
      glacierAria: 'Мұздықтың қарапайым көлденең қимасы',
      coastAria: 'Жағалау мен теңіз деңгейінің қарапайым сызбасы',
      habitatAria: 'Су, өсімдіктер, жәндіктер мен құстарды байланыстыратын мекен ету ортасының қарапайым желісі',
      habitatGraphAria: 'Мекен ету ортасы желісінің сызбасы',
      oceanChemistryAria: 'Мұхит химиясы ұғымының қарапайым сызбасы',
      wildfireRiskAria: 'Құрғақ өсімдіктер мен өрт қаупінің қарапайым сызбасы',
      droughtAria: 'Құрғақ жер мен жауын-шашынның қарапайым сызбасы',
    },
  },
} as const;
