export type ProductLocale = 'en' | 'kk';

export const productCopy = {
  en: {
    home: {
      nav: { home: 'Home', learn: 'Learn', challenges: 'Challenges', game: 'Eco Game', action: 'Eco Action', progress: 'My Progress', method: 'Method', sections: 'Product sections' },
      heroEyebrow: 'EcoPulse / Learn · Understand · Act',
      heroTitle: 'Learn English.\nUnderstand Earth.\nMake a difference.',
      heroBody: 'Improve your English while discovering how your everyday choices affect our planet.',
      heroStart: 'Start learning',
      heroSystem: 'Test your eco-knowledge',
      scroll: 'Explore the planet',
      welcomeEyebrow: 'Welcome / EcoPulse',
      welcomeTitle: 'Welcome to EcoPulse!',
      welcomeSubtitle: 'Where English meets environmental awareness.',
      welcomePoints: ['Learn useful English.', 'Discover real environmental problems.', 'Make smarter choices for our planet.'],
      welcomeAction: 'Start your journey →',
      topicsEyebrow: 'Choose your path',
      topicsTitle: 'What do you want to learn about?',
      topicsBody: 'Eight connected environmental themes. Start anywhere and build the language to explain what is happening to our planet.',
      topicsAction: 'Learn →',
      connectionEyebrow: 'Explore connections / 01',
      connectionTitle: "Don't learn\nwords alone.",
      connectionBody: 'A translation is only the first layer. EcoPulse turns vocabulary into relationships you can explain and use.',
      connectionCta: 'Learn the word. Understand the phenomenon. Find the connection.',
      firstLesson: 'Try the first lesson →',
      demoEyebrow: 'Try EcoPulse / no sign-in',
      demoTitle: 'One word.\nThen a\nconnection.',
      demoBody: 'Answer a real EcoPulse question. This demo is practice only — it does not change XP or mastery.',
      demoLanguage: 'Demo language',
      liveDemo: 'Live demo',
      answer: 'Answer',
      correct: 'Correct',
      loopEyebrow: 'The EcoPulse loop',
      loopTitle: 'Learn it.\nConnect it.\nUse it.',
      loopItems: [
        { title: 'Learn', body: 'Discover the English word, pronunciation and clear Kazakh support when you need it.' },
        { title: 'Connect', body: 'See how one concept relates to weather, climate, water, habitats and other systems.' },
        { title: 'Think', body: 'Use evidence and context instead of memorising an isolated correct answer.' },
        { title: 'Act', body: 'Take knowledge off-screen with small, safe and optional observation missions.' },
      ],
      actionEyebrow: 'Off-screen / optional',
      actionTitle: 'From knowledge\nto action.',
      waterWatch: 'Water Watch',
      waterWatchBody: 'Notice one moment today when water could be used more carefully.',
      minutes: 'min',
      noPhoto: 'No photo',
      noLocation: 'No location',
      finalEyebrow: 'Your first connection is ready',
      finalTitle: 'Start\nyour pulse.',
      finalAction: 'Begin →',
    },
    learn: {
      loadingEyebrow: 'Your next pulse',
      loading: 'Loading\nyour path…',
      memoryDue: 'Memory / due',
      coreConnected: 'EcoPulse / core',
      lessonsConnected: '8 lessons connected',
      worldsEyebrow: 'Four connected worlds',
      worldsTitle: 'Enter the\nsystem.',
      lessons: 'lessons',
      journeyEyebrow: 'The system',
      journeyTitle: 'Follow the\nconnections.',
      checkpointsEyebrow: 'Reasoning challenges',
      checkpointsTitle: 'Think beyond\nthe word.',
      coreWord: 'core word',
      coreWords: 'core words',
      optionalMission: 'optional mission',
      actOptional: 'Act / optional',
      status: { connected: 'Connected', checkpointReady: 'Checkpoint ready', inProgress: 'In progress', explore: 'Explore', next: 'Next', available: 'Available', locked: 'Locked' },
      open: 'Open →',
      review: 'Review →',
      enter: 'Enter →',
      completeWorldFirst: 'Complete this world first',
      decisions: 'decisions',
    },
    review: {
      loading: 'Loading your pulse…',
      clearEyebrow: 'Review / clear',
      clearTitle: 'Nothing due.',
      clearBody: 'Your current review queue is clear. Complete a lesson to add words to spaced review.',
      clearAction: 'Continue learning →',
      completeEyebrow: 'Review / complete',
      completeTitle: 'Memory refreshed.',
      completeBody: 'Your next review dates were scheduled from today’s answers. Mastery changes only when different kinds of evidence are demonstrated over time.',
      completeAction: 'See My Progress →',
      remainingTitle: 'More review is due.',
      remainingBody: '{count} words are still due today. Take another focused batch when you are ready.',
      continueReview: 'Continue review →',
      chooseKazakh: 'Choose the best Kazakh meaning.',
      completeEnglish: 'Complete the sentence in English.',
      typeEnglish: 'Type the English word from memory.',
      inputLabel: 'English answer',
      inputPlaceholder: 'Type your answer',
      check: 'Check →',
      next: 'Next →',
      strengthened: 'Evidence strengthened.',
      relearning: 'Relearning scheduled.',
      answerPrefix: 'Answer',
      modes: {
        recall: 'Recall',
        context: 'Use in context',
        recognition: 'Recognize',
        delayed: 'Delayed recall',
      },
    },
    pulse: {
      loading: 'Loading your pulse…',
      eyebrow: 'Your EcoPulse',
      title: 'Activity level',
      xpNote: 'Pulse XP · activity progression, not a knowledge score.',
      heartLabel: 'Learning + action',
      language: 'Language',
      masteredWords: 'mastered words',
      strong: 'Strong',
      strongWords: 'strong words',
      planet: 'Planet',
      connectedConcepts: 'connected concepts',
      think: 'Think',
      scenarios: 'scenarios',
      challenges: 'challenges',
      act: 'Act',
      missionsCompleted: 'missions completed',
      nextAction: 'Next best action',
      settings: 'Learning settings →',
      start: 'Start →',
    },
    explore: {
      eyebrow: 'Explore / concept map',
      title: 'See how\nthe planet\nconnects.',
      body: 'Every line has a meaning: related to, contributes to, affects, or forms part of a larger system.',
    },
    challenges: {
      eyebrow: 'Challenges / thinking lab',
      title: 'Think beyond\nthe word.',
      body: 'Complete connected worlds, then make evidence-based decisions and explain the relationship in English.',
    },
    challengeRun: {
      loading: 'Loading checkpoint…',
      eyebrow: 'World challenge',
      lockedEyebrow: 'World challenge / locked',
      lockedTitle: 'Connect the world first.',
      lockedBody: 'Complete the lessons in this world before entering its checkpoint.',
      backLearn: 'Back to Learn →',
      connected: 'World connected',
      completeBody: 'You completed this checkpoint. Its +50 Pulse XP can only be earned once.',
      explore: 'Explore connections',
      begin: 'Begin checkpoint →',
      minutes: 'min',
      decisions: 'decisions',
      languageControls: 'Language controls',
      reasoningEyebrow: 'Checkpoint / explain',
      reasoningTitle: 'Explain the connection.',
      reasoningBody: 'Write one short explanation in English. EcoPulse checks that you attempted the reasoning; it does not grade your opinion.',
      reasoningPlaceholder: 'Because…',
      reasoningMinimum: 'Write at least three words',
      reasoningReady: 'Reasoning ready',
      completeCheckpoint: 'Complete checkpoint →',
    },
    missions: {
      completed: 'Completed',
      optional: 'Off-screen / optional',
      minutes: 'min',
      noPhoto: 'No photo',
      noLocation: 'No location',
      reflection: 'Optional reflection',
      reflectionPlaceholder: 'Write one short thought in English…',
      guestStored: 'Guest mode · stored on this device',
      missionComplete: 'Mission complete ✓',
      saveReflection: 'Save reflection',
      reflectionSaved: 'Reflection saved',
      addReflection: 'Add reflection',
      loading: 'Loading…',
      completeMission: 'Complete mission →',
      noProof: 'No proof required. Observe safely in a place that is already part of your normal day.',
      safetyMetaAria: 'Mission safety and time information',
      completeBody: 'Your observation is recorded on this device. Mission XP can only be earned once.',
      seePulse: 'See My Progress →',
      allMissions: 'All missions →',
    },
    notFound: {
      eyebrow: 'Connection / not found',
      title: 'Lost the\nconnection?',
      body: 'This path is not part of the EcoPulse map. Return to the learning system or start again from Earth.',
      learn: 'Back to Learn →',
      home: 'EcoPulse home',
    },
    error: {
      eyebrow: 'Connection / interrupted',
      title: 'The connection\nwas interrupted.',
      body: 'EcoPulse could not finish this screen. Your local learning state is kept separately, so you can retry or return home.',
      retry: 'Try again →',
      home: 'EcoPulse home',
      loading: 'Reconnecting the learning system…',
    },
    concept: {
      concept: 'Concept',
      discovered: '● Connection discovered',
      notDiscovered: '○ Connection not yet discovered',
      mastery: 'Vocabulary mastery',
      loading: 'Loading',
      masteryBody: 'No percentage score. EcoPulse shows the evidence you have actually demonstrated.',
      evidenceFound: 'Evidence found',
      stillToProve: 'Still to prove',
      evidenceLabels: { recognition: 'Recognize', recall: 'Recall', context: 'Context', delayedReview: 'Delayed review' },
      semanticConnections: 'Semantic connections',
      connectionsTitle: 'See what\nconnects.',
      sources: 'How do we know?',
      sourceTitle: 'Source\nlayer.',
      checked: 'Checked',
      nextConnection: 'Next connection',
      keepMoving: 'Keep the\nsystem moving.',
      openLesson: 'Open lesson →',
      reviewVocabulary: 'Review vocabulary →',
      backExplore: 'Back to Explore →',
    },
  },
  kk: {
    home: {
      nav: { home: 'Басты бет', learn: 'Оқу', challenges: 'Сынақтар', game: 'Eco Game', action: 'Eco Action', progress: 'Менің прогресім', method: 'Әдіс', sections: 'Өнім бөлімдері' },
      heroEyebrow: 'EcoPulse / Үйрен · Түсін · Әрекет ет',
      heroTitle: 'Ағылшын тілін үйрен.\nЖерді түсін.\nӨзгеріс жаса.',
      heroBody: 'Ағылшын тіліңді жетілдіріп, күнделікті таңдауларыңның планетамызға қалай әсер ететінін зертте.',
      heroStart: 'Оқуды бастау',
      heroSystem: 'Eco-біліміңді тексер',
      scroll: 'Планетаны зертте',
      welcomeEyebrow: 'Қош келдің / EcoPulse',
      welcomeTitle: 'EcoPulse-қа қош келдің!',
      welcomeSubtitle: 'Ағылшын тілі мен экологиялық сананың тоғысқан жері.',
      welcomePoints: ['Пайдалы ағылшын тілін үйрен.', 'Нақты экологиялық мәселелерді зертте.', 'Планетамыз үшін ақылдырақ таңдау жаса.'],
      welcomeAction: 'Саяхатыңды баста →',
      topicsEyebrow: 'Бағытыңды таңда',
      topicsTitle: 'Не туралы үйренгің келеді?',
      topicsBody: 'Бір-бірімен байланысқан сегіз экологиялық тақырып. Кез келгенінен бастап, планетада не болып жатқанын түсіндіретін тілді меңгер.',
      topicsAction: 'Үйрен →',
      connectionEyebrow: 'Байланыс қозғалтқышы / 01',
      connectionTitle: 'Сөздерді\nжеке үйренбе.',
      connectionBody: 'Аударма — тек бірінші қабат. EcoPulse сөздерді түсіндіріп, қолдана алатын байланыстар жүйесіне айналдырады.',
      connectionCta: 'Сөзді үйрен. Құбылысты түсін. Байланысын тап.',
      firstLesson: 'Алғашқы сабақты көру →',
      demoEyebrow: 'EcoPulse-ты байқап көр / кіру қажет емес',
      demoTitle: 'Бір сөз.\nСодан кейін\nбайланыс.',
      demoBody: 'Нақты EcoPulse сұрағына жауап бер. Бұл тек жаттығу — XP немесе mastery өзгермейді.',
      demoLanguage: 'Демо тілі',
      liveDemo: 'Тікелей демо',
      answer: 'Жауап',
      correct: 'Дұрыс',
      loopEyebrow: 'EcoPulse циклі',
      loopTitle: 'Үйрен.\nБайланыстыр.\nҚолдан.',
      loopItems: [
        { title: 'Үйрен', body: 'Ағылшын сөзін, айтылуын және қажет кезде анық қазақша қолдауды үйрен.' },
        { title: 'Байланыстыр', body: 'Бір ұғымның ауа райы, климат, су, табиғи орта және басқа жүйелермен байланысын көр.' },
        { title: 'Ойлан', body: 'Жеке дұрыс жауапты жаттаудың орнына дәлел мен контексті қолдан.' },
        { title: 'Әрекет ет', body: 'Кішкентай, қауіпсіз және міндетті емес бақылау миссияларымен біліміңді экраннан тыс қолдан.' },
      ],
      actionEyebrow: 'Экраннан тыс / міндетті емес',
      actionTitle: 'Білімнен\nәрекетке.',
      waterWatch: 'Суды бақылау',
      waterWatchBody: 'Бүгін суды ұқыптырақ пайдалануға болатын бір сәтті байқа.',
      minutes: 'мин',
      noPhoto: 'Фото қажет емес',
      noLocation: 'Орналасу қажет емес',
      finalEyebrow: 'Алғашқы байланыс дайын',
      finalTitle: 'Pulse-ыңды\nбаста.',
      finalAction: 'Бастау →',
    },
    learn: {
      loadingEyebrow: 'Келесі қадам',
      loading: 'Жолың\nжүктелуде…',
      memoryDue: 'Жад / қайталау',
      coreConnected: 'EcoPulse / негізгі',
      lessonsConnected: '8 сабақ байланыстырылды',
      worldsEyebrow: 'Төрт байланысқан әлем',
      worldsTitle: 'Жүйеге\nкір.',
      lessons: 'сабақ',
      journeyEyebrow: 'Жүйе',
      journeyTitle: 'Байланыстарды\nжалғастыр.',
      checkpointsEyebrow: 'Әлемдік бақылаулар',
      checkpointsTitle: 'Сөзден ары\nойлан.',
      coreWord: 'негізгі сөз',
      coreWords: 'негізгі сөз',
      optionalMission: 'міндетті емес миссия',
      actOptional: 'Әрекет / міндетті емес',
      status: { connected: 'Байланысты', checkpointReady: 'Бақылауға дайын', inProgress: 'Орындалуда', explore: 'Зерттеу', next: 'Келесі', available: 'Қолжетімді', locked: 'Жабық' },
      open: 'Ашу →',
      review: 'Қайталау →',
      enter: 'Кіру →',
      completeWorldFirst: 'Алдымен осы әлемді аяқта',
      decisions: 'шешім',
    },
    review: {
      loading: 'Pulse жүктелуде…',
      clearEyebrow: 'Қайталау / дайын',
      clearTitle: 'Қайталау жоқ.',
      clearBody: 'Қазір қайталау кезегінде сөз жоқ. Интервалдық қайталауға жаңа сөздер қосу үшін сабақты аяқта.',
      clearAction: 'Оқуды жалғастыру →',
      completeEyebrow: 'Қайталау / аяқталды',
      completeTitle: 'Білім жаңартылды.',
      completeBody: 'Келесі қайталау күндері бүгінгі жауаптарыңа қарай жоспарланды. Mastery әртүрлі дәлел түрлері уақыт өте көрсетілгенде ғана өзгереді.',
      completeAction: 'Менің Pulse-ымды көру →',
      remainingTitle: 'Тағы қайталау бар.',
      remainingBody: 'Бүгін тағы {count} сөз қайталауды қажет етеді. Дайын болғанда келесі қысқа топтаманы баста.',
      continueReview: 'Қайталауды жалғастыру →',
      chooseKazakh: 'Ең дұрыс қазақша мағынаны таңда.',
      completeEnglish: 'Сөйлемді ағылшын тілінде толықтыр.',
      typeEnglish: 'Ағылшын сөзін есте сақтап жаз.',
      inputLabel: 'Ағылшынша жауап',
      inputPlaceholder: 'Жауабыңды жаз',
      check: 'Тексеру →',
      next: 'Келесі →',
      strengthened: 'Дәлел күшейді.',
      relearning: 'Қайта оқу жоспарланды.',
      answerPrefix: 'Жауап',
      modes: {
        recall: 'Еске түсіру',
        context: 'Контексте қолдану',
        recognition: 'Тану',
        delayed: 'Кейінгі еске түсіру',
      },
    },
    pulse: {
      loading: 'Pulse жүктелуде…',
      eyebrow: 'Сенің EcoPulse-ың',
      title: 'Pulse деңгейі',
      xpNote: 'Pulse XP · бұл белсенділік прогресі, білім бағасы емес.',
      heartLabel: 'Оқу + әрекет',
      language: 'Тіл',
      masteredWords: 'меңгерілген сөз',
      strong: 'Мықты',
      strongWords: 'мықты сөз',
      planet: 'Планета',
      connectedConcepts: 'байланысқан ұғым',
      think: 'Ойлау',
      scenarios: 'сценарий',
      challenges: 'челлендж',
      act: 'Әрекет',
      missionsCompleted: 'аяқталған миссия',
      nextAction: 'Келесі ең жақсы қадам',
      settings: 'Оқу баптаулары →',
      start: 'Бастау →',
    },
    explore: {
      eyebrow: 'Байланыс қозғалтқышы / карта',
      title: 'Планетаның\nқалай байланысатынын\nкөр.',
      body: 'Әр сызықтың мағынасы бар: байланысты, ықпал етеді, әсер етеді немесе үлкен жүйенің бөлігі болады.',
    },
    challenges: {
      eyebrow: 'Әрекет / міндетті емес',
      title: 'Біліміңді\nэкраннан\nтыс қолдан.',
      body: 'Кішкентай әрі қауіпсіз бақылаулар. GPS жоқ, міндетті фото жоқ, қысым жоқ.',
    },
    challengeRun: {
      loading: 'Бақылау кезеңі жүктелуде…',
      eyebrow: 'Әлемдік челлендж',
      lockedEyebrow: 'Әлемдік челлендж / жабық',
      lockedTitle: 'Алдымен әлемді байланыстыр.',
      lockedBody: 'Бұл бақылау кезеңіне кірмес бұрын осы әлемнің сабақтарын аяқта.',
      backLearn: 'Оқуға оралу →',
      connected: 'Әлем байланыстырылды',
      completeBody: 'Сен бұл бақылау кезеңін аяқтадың. +50 Pulse XP тек бір рет беріледі.',
      explore: 'Байланыстарды зерттеу',
      begin: 'Бақылауды бастау →',
      minutes: 'мин',
      decisions: 'шешім',
      languageControls: 'Тіл параметрлері',
      reasoningEyebrow: 'Бақылау кезеңі / түсіндір',
      reasoningTitle: 'Байланысты түсіндір.',
      reasoningBody: 'Ағылшын тілінде бір қысқа түсініктеме жаз. EcoPulse reasoning әрекетін ғана тексереді, пікіріңді бағаламайды.',
      reasoningPlaceholder: 'Because…',
      reasoningMinimum: 'Кемінде үш сөз жаз',
      reasoningReady: 'Түсіндіру дайын',
      completeCheckpoint: 'Бақылау кезеңін аяқтау →',
    },
    missions: {
      completed: 'Аяқталды',
      optional: 'Экраннан тыс / міндетті емес',
      minutes: 'мин',
      noPhoto: 'Фото қажет емес',
      noLocation: 'Орналасу қажет емес',
      reflection: 'Қосымша рефлексия',
      reflectionPlaceholder: 'Ағылшын тілінде бір қысқа ой жаз…',
      guestStored: 'Қонақ режимі · осы құрылғыда сақталады',
      missionComplete: 'Миссия аяқталды ✓',
      saveReflection: 'Рефлексияны сақтау',
      reflectionSaved: 'Рефлексия сақталды',
      addReflection: 'Рефлексия қосу',
      loading: 'Жүктелуде…',
      completeMission: 'Миссияны аяқтау →',
      noProof: 'Дәлел қажет емес. Күнделікті қауіпсіз баратын жерде ғана бақыла.',
      safetyMetaAria: 'Миссияның қауіпсіздігі мен уақыты туралы ақпарат',
      completeBody: 'Бақылауың осы құрылғыда сақталды. Миссия XP-і тек бір рет беріледі.',
      seePulse: 'My Pulse-ты көру →',
      allMissions: 'Барлық миссия →',
    },
    notFound: {
      eyebrow: 'Байланыс / табылмады',
      title: 'Байланыс\nжоғалды ма?',
      body: 'Бұл жол EcoPulse картасына кірмейді. Оқу жүйесіне орал немесе Жерден қайта баста.',
      learn: 'Оқуға оралу →',
      home: 'EcoPulse басты беті',
    },
    error: {
      eyebrow: 'Байланыс / үзілді',
      title: 'Байланыс\nүзілді.',
      body: 'EcoPulse бұл экранды аяқтай алмады. Жергілікті оқу күйі бөлек сақталады, сондықтан қайта көруге немесе басты бетке оралуға болады.',
      retry: 'Қайта көру →',
      home: 'EcoPulse басты беті',
      loading: 'Оқу жүйесі қайта байланыстырылуда…',
    },
    concept: {
      concept: 'Ұғым',
      discovered: '● Байланыс ашылды',
      notDiscovered: '○ Байланыс әлі ашылмады',
      mastery: 'Сөзді меңгеру',
      loading: 'Жүктелуде',
      masteryBody: 'Пайыздық баға жоқ. EcoPulse сен нақты көрсеткен дәлелдерді ғана көрсетеді.',
      evidenceFound: 'Дәлел бар',
      stillToProve: 'Әлі дәлелдеу керек',
      evidenceLabels: { recognition: 'Тану', recall: 'Еске түсіру', context: 'Контекст', delayedReview: 'Кейінгі қайталау' },
      semanticConnections: 'Мағыналық байланыстар',
      connectionsTitle: 'Немен\nбайланысатынын көр.',
      sources: 'Мұны қайдан білеміз?',
      sourceTitle: 'Дереккөз\nқабаты.',
      checked: 'Тексерілген',
      nextConnection: 'Келесі байланыс',
      keepMoving: 'Жүйені\nжалғастыр.',
      openLesson: 'Сабақты ашу →',
      reviewVocabulary: 'Сөздерді қайталау →',
      backExplore: 'Зерттеуге оралу →',
    },
  },
} as const;

export const relationLabels = {
  causes: { en: 'causes', kk: 'тудырады' },
  contributes_to: { en: 'contributes to', kk: 'ықпал етеді' },
  affects: { en: 'affects', kk: 'әсер етеді' },
  part_of: { en: 'part of', kk: 'бөлігі' },
  related_to: { en: 'related to', kk: 'байланысты' },
  depends_on: { en: 'depends on', kk: 'тәуелді' },
  example_of: { en: 'example of', kk: 'мысалы' },
  absorbed_by: { en: 'absorbed by', kk: 'сіңіріледі' },
} as const;
